### ISSUE TITLE
kohonen_distance missing const for some arguments

### ISSUE THREAD

**Issue by jura-gresko** [panda-official/metric#110]
missing **const**

https://github.com/panda-official/metric/blob/53c8be37f7a0d05906b0a5335288fd5cae502f39/modules/distance/k-structured/kohonen_distance.cpp#L37

https://github.com/panda-official/metric/blob/53c8be37f7a0d05906b0a5335288fd5cae502f39/modules/distance/k-structured/kohonen_distance.cpp#L52

**Comment by Stepka** [comment]
Fixed by https://github.com/panda-official/metric/commit/3387cd64fee88df3fc6eade71296e73bb770a2db

**Comment by jura-gresko** [comment]
@Stepka I don't see any changes in mentioned file
