### ISSUE TITLE
ESN should support generic containers

### ISSUE THREAD

**Issue by eduard-stack** [panda-official/metric#112]
https://github.com/panda-official/metric/blob/6f8350a8667c51d725dccbae925608e68a00df2c/modules/mapping/ESN.hpp#L111

https://github.com/panda-official/metric/blob/6f8350a8667c51d725dccbae925608e68a00df2c/modules/mapping/ESN.hpp#L120

https://github.com/panda-official/metric/blob/6f8350a8667c51d725dccbae925608e68a00df2c/modules/mapping/ESN.hpp#L128

**Comment by LeilaPiri** [comment]
@dv14 please check this issue

**Comment by maxfilippov** [comment]
I found std::vector input implemented via vector_to_blaze converter function. Not sure if non-Blaze ESN implementation (that natively uses std::vector<recType>) is easy to add and needed to be added (?).

**Comment by maxfilippov** [comment]
ESN supports generic containers via converter
