### ISSUE TITLE
Asserts doesn't play well with python in production

### ISSUE THREAD

**Issue by jura-gresko** [panda-official/metric#148]
In general `assert` are fine when we do testing and debugging, but in production when the program crash only because function parameters incorrect is not very friendly.
We need to decide two things:
1. will we replace asserts with something else or just remove?
2.1 Yes, what should be the replacement?
2.2 No, will the code be correct and safe enough without them?

**Comment by mkh-welsch** [comment]
what about a macro controlled verbose flag to have asserts or not?

**Comment by dv14** [comment]
assert's behavior is controlled by NDEBUG macro. This macro defined by cmake in Release builds. And as far as I know MSVC also define this macro in Release. So there is no asserts  in production.

**Comment by mkh-welsch** [comment]
@dv14 I assigned you, can you search for all asserts and set the macro?

**Comment by dv14** [comment]
There is no need to set macro by hand. 
Common practice is to set Release mode in build system at build moment.
For cmake Release mode controlled by CMAKE_BUILD_TYPE variable.
`cmake -DCMAKE_BUILD_TYPE=Release build_dir`

**Comment by jura-gresko** [comment]
@dv14 so the problem is with setuptools or cmake for python folder I guess, it doesn't strip asserts.

**Comment by jura-gresko** [comment]
ok, I found the problem in configuration, thanks guys
