### ISSUE TITLE
1. Add JSON and CSV support

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#20]
- add reader and writer functions to utils modules.
- update examples
- update dependencies.

**Comment by SignalEmpoweringTechnology** [comment]
and Dataset class to load easy load demo data

**Comment by victor1234** [comment]
I added json lib. And added json support to dnn module too. What else should be done in this task?

**Comment by mkh-welsch** [comment]
add a clever CSV data reader for matrix-like data, where every row represents a record, and simple writer to store data again.

for example, use regex to parse data intelligent, here I have a javascript snippet:
``` javascript
function parseNumArray(str) {
  str = str.replace(/^\s+|\s+$/g, '');
  str = str.replace(/^\[|\]$/g, '');

  var getSeparator = function (str) {
    if (str.match(/[,|.].*;/)) {
      return /\s*;\s*/;
    }

    var spaceSep = /\s+/;

    if (str.match(/\..*,/) || str.match(/,.*\./) ) {
      if (str.match(/\s/)) {

        if (str.match(/\s+,|,\s+/)) {
          return /\s+,|,\s+/;
        }

        var commaSep = /\s*,\s*/;

        var spaceLen = str.split(spaceSep).length;
        var commaLen = str.split(commaSep).length;

        if (spaceLen > commaLen) {
          return spaceSep;
        }

        return commaSep;
      }
      return /,/;
    }

    return spaceSep;
  }

  var separator = getSeparator(str);

  return str
    .split(separator)
    .filter(function(val) {
      return val.length > 0;
    })
    .map(function(val) {
      var val = val.replace(/^\s+|\s+$/g, '');

      if (val.match(/,/)) {
        val = val.replace(/,/, '.');
      }

      return Number(val);
    });
}

export { parseNumArray };

  // tests
  // function testStr(str, expect) {
  //   var parsedArr = parseNumArray(str);
  //   // console.log(str, ' => ',
  //   //   parsedArr, ' => ',
  //   //   JSON.stringify(parsedArr) === JSON.stringify(expect));
  // }
  
  // testStr(" 1,1 1,2 3,4 15,6 ", [1.1,1.2,3.4,15.6]);
  // testStr(" 0.1 1.2 3.4 5.6", [0.1,1.2,3.4,5.6]);
  // testStr("1,1\n1,2\n3,4\n15\n", [1.1,1.2,3.4,15]);
  // testStr("1,1;1,2; 3,4;15;", [1.1,1.2,3.4,15]);
  // testStr("9.111;1.2 ;3.4;15;", [9.111,1.2,3.4,15]);
  // testStr(" 1 1 3 4 5", [1,1,3,4,5]);
  // testStr("[1 ,1 , 3 , 4.5 ,5]", [1,1,3,4.5,5]);
  // testStr("1,2.3,4.5,6,7,", [1,2.3,4.5,6,7]);
  // testStr("1.2 1.2 1,3 1.5 1.6 1.7 1.8", [1.2,1.2,1.3,1.5,1.6,1.7,1.8]);
  // testStr("1,2.3,4.a,6,7", [1,2.3,NaN,6,7]);
  // testStr(".4 2.3 .6 5.7", [0.4,2.3,0.6,5.7]);
```

**Comment by victor1234** [comment]
May be we should add >> and << operators for blaze types? To easy use them for data print and import?

**Comment by mkh-welsch** [comment]
blaze types already have these plot functions <<.. or do you mean something different?

**Comment by mkh-welsch** [comment]
the problem with TSV and CSV files is that they are always a bit different. sometimes with header, sometimes without. in addition, in germany point and comma as decimal separators can be mixed up arbitrarily from case to case.
I think it is a good way to parse the data directly into a Blaze type. a matrix or a vector depending on the number of columns. Also, it might be nice to parse into a sparse matrix if there is no number between two separators.

**Comment by victor1234** [comment]
`blaze::DenseMatrix loadFromDsvFile(filepath, delimiter=",", commentChar="#", skipFirstRows=0)`
In dense matrix case we could replace doubled decimals to single because user could use multiple decimals to align data. But how to be in sparce matrix case?
What checks we should add to dsv data? Same row/column length for all rows/columns? All elements must be numeric? What else?
Only decimal values will be supported?
