### ISSUE TITLE
change MSCV c++ version in python wrapper to avoid problems with std::result_of

### ISSUE THREAD

**Issue by n8asyl** [panda-official/metric#218]
python/CMakeLists.txt sets the c++ standart to latest. However in c++20 std::result_of was removed/replaced, which caused me some compilation errors related to 3party libs. Changing the setting to c++17 solved this issue.

Line 23: set(PYBIND11_CPP_STANDARD /std:c++latest) # Enables some MSVC C++17 features
->
set(PYBIND11_CPP_STANDARD /std:c++17) # Enables some MSVC C++17 features

**Comment by eugene-kulak** [comment]
@n8asyl thanks for the report, the issue has being fixed in the https://github.com/panda-official/metric/commit/e5df0adee32dd474684ca839346de229a8afab7e and merged to master
