### ISSUE TITLE
Add KNN-graph (local density matrix) 

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#23]
to sparse graph representation in space module and refactor functions that are using it.

**Comment by SignalEmpoweringTechnology** [comment]
for direct construction:
http://cs.uef.fi/sipu/pub/FastKNN-ICBDC2018.pdf
https://github.com/fmaglia/LSH_kNN_graph

**Comment by SignalEmpoweringTechnology** [comment]
for next neighbor search in knn-graph:
https://www.ijcai.org/Proceedings/11/Papers/222.pdf
https://github.com/ristuo/gnns
