### ISSUE TITLE
add 2d wavelet support

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#28]

**Comment by SignalEmpoweringTechnology** [comment]
possible source: https://github.com/vm1414/FYP/blob/456f75fe2fd6069e7a47da98c078f7878ea18c28/UFRESH_2X/Testing_Images/fresh_c%2B%2B/src/wavelet.hpp

has to be checked with Matlab build-in results.

**Comment by maxfilippov** [comment]
added initial DWT2 code, branch iss28_dwt2
