### ISSUE TITLE
update Wavelet API

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#29]
- use wavelet structs instead of wavelet integers. 
- integrate wavelet structs build functions

**Comment by maxfilippov** [comment]
adding support of Blaze vectors as in PCFA and DSPCC

**Comment by maxfilippov** [comment]
made pull reqiest #82 https://github.com/panda-official/metric/pull/82 where old version of wavelet.*pp is completely removed and all the dependent code is updated. Although, this pull request does not closes the issue: wavelet structures are still not developed
