### ISSUE TITLE
rework the entropy computation

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#30]
find a better solution to compute the differential entropy

**Comment by mkh-welsch** [comment]
in addition the entropy should be calculated directly on a KNN representation of a metric space. for graph regard also the KNN issue here: https://github.com/panda-official/metric/issues/23

**Comment by mkh-welsch** [comment]
and entropy should have an Input for search tree representation in addition

**Comment by mkh-welsch** [comment]
![entropy_rescale](https://user-images.githubusercontent.com/24566838/69484888-af495e80-0e38-11ea-865f-de200a6f8908.png)

because of the differential entropy can go down to -Inf, which is strange for a entropy measure on first view, we should rescale the entropy for values less then 1 with exponential function. we will leave a comment, how to redo it to get the original differential entropy.

if (entropy <1)
entropy = 1/exp(1)*exp(entropy)

**Comment by mkh-welsch** [comment]
remove noise generator from entropy function.

**Comment by maxfilippov** [comment]
I've created branch iss30_entropy for this issue, there I've removed noise in entropy function, added compatibility with strings and example with Edit metric

**Comment by maxfilippov** [comment]
Added 1/exp(1)*exp(entropy) conditional conversion to entropy function and reverse log(converted_entropy) + 1 conversion to its calls in VOI and other functions. entropy_kl and related functions are left untouched

**Comment by maxfilippov** [comment]
Also updated types in entropy_kl the same way as previously in entropy
