### ISSUE TITLE
PCA compressor restore level bug

### ISSUE THREAD

**Issue by SignalEmpoweringTechnology** [panda-official/metric#31]
when decoding a curve one get a wrong median level, if the original data is not normalized.

**Comment by maxfilippov** [comment]
Added saving the average curve (the position of the new center point in the space of curves). Now the saved original average curve is added to restored curves, i e they are shifted to the original center point

**Comment by maxfilippov** [comment]
The main problem was in the completely wrong normalization procedure inside PCA function. Fixed.
