### ISSUE TITLE
add python wrapper

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#35]

**Comment by iluxa** [comment]
Initial python wrapper implementation is on branch https://github.com/panda-official/metric/tree/issue_35
implemented correlation module wrapper supported only
wrapper accepts only python lists: tuples, numpy and pandas container support need to be implemented

**Comment by iluxa** [comment]
implemented `metric::MGC` python wrapper: python lists and nympy arrays are supported

**Comment by iluxa** [comment]
https://github.com/panda-official/metric/commit/ecb0b46191e3ef327d507874d07d362b0d172998
changes:
* split wrapper to modules(files)
* metric::Entropy wrapper partial implementation
* metric_MGC macro metrics
* Readme changed for build and install wheel module
* metric::EMD initial implementation

**Comment by iluxa** [comment]
metric::EMD wrapper implemetation:
https://github.com/panda-official/metric/commit/819d47b7732b18259f4045315aed51001e05c273

**Comment by iluxa** [comment]
VOI_kl and VOI_normalized wrappers implementation:
https://github.com/panda-official/metric/commit/5ec9c83f69655221c76dc6ab24ccef7d21238a21
