### ISSUE TITLE
delayed correlation vector

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#39]
in MGC module, add a method to compute the delayed correlation vector.
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/24566838/68544636-869b8080-03c5-11ea-9ed4-9d0804e2a0fa.png">

**Comment by SignalEmpoweringTechnology** [comment]
looks like I reinvented the cross correlation. ^^
https://de.mathworks.com/help/matlab/ref/xcorr.html

but of course, it's metric cross correlation now.
