### ISSUE TITLE
Histogram of oriented gradients (HOG) algorithm

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/metric#42]
Please implement an HOG algorithm. 
Results of this algorithm will be used for EMD metric.

https://en.wikipedia.org/wiki/Histogram_of_oriented_gradients
https://de.mathworks.com/help/vision/ref/extracthogfeatures.html 

[histograms-of-oriented-gradients-for-human-detection.pdf](https://github.com/panda-official/metric/files/3874862/histograms-of-oriented-gradients-for-human-detection.pdf)

**Comment by mkh-welsch** [comment]
SIMD optimized version here:

http://ermig1979.github.io/Simd/help/group__hog.html#details
https://github.com/ermig1979/Simd/blob/master/src/Simd/SimdAvx2Hog.cpp

**Comment by mkh-welsch** [comment]
Julia reference implementation: https://github.com/JuliaImages/ImageFeatures.jl/blob/master/src/hog.jl
