### ISSUE TITLE
add model store and load methods

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/metric#44]
https://uscilab.github.io/cereal/

**Comment by victor1234** [comment]
Should model structures be saved  besides the parameters?

**Comment by mkh-welsch** [comment]
Yes, I guess so. The weights without the corresponding structures don't seem so useful to me.

**Comment by victor1234** [comment]
Dnn could save/load model structure in json and weights by cereal. Do we need additional work?

**Comment by mkh-welsch** [comment]
no.
