### ISSUE TITLE
EMD::operator(): too strong argument constraints

### ISSUE THREAD

**Issue by iluxa** [panda-official/metric#73]
The operator has a call:
```
return EMD_details::emd_impl<Container, FLOW_TYPE>()(Pc, Qc, P, Q, C, extra_mass_penalty, F);
```
where Pc and Qc required to be std::vector (because P and Q are vectors)
The requirement to be a vector is too strong to implement Python wrapper for the algorithm.
Required constraints: container that allows index-based random access.

**Comment by Stepka** [comment]
Pushed fix with "bug_fixes' branch. Please, check if all is ok.

**Comment by iluxa** [comment]
Pushed fix https://github.com/panda-official/metric/commit/3206485c9184d100646a2aa7c09c0683b5e79d2a
now it is ok
