### ISSUE TITLE
Build process on Raspberry PI & Windows

### ISSUE THREAD

**Issue by sahranas** [panda-official/metric#88]
The build process seems to take too much memory on a raspberry pi, since it freezes everythime the wheel is building. 
Needs to be optimized otherwise unusable for raspberry pi.
The building process should also be compatible for Windows
.

**Comment by iluxa** [comment]
Python module build process split into several translation units: commit https://github.com/panda-official/metric/commit/bf6b21b46863f756f4dd9f5b01282dbc099506d2
Python module build takes about 18 minutes on RPi3 with 100M swap memory on
it doesn't build without swap with 1Gb RAM
command to build on RPi3:

```
MAKE="make -j1" python3 setup.py bdist_wheel
```
