### ISSUE TITLE
ESN implementation is blaze-specific, but need to support any stl-like random-access container

### ISSUE THREAD

**Issue by iluxa** [panda-official/metric#97]

**Comment by maxfilippov** [comment]
Added template parameters <recType, Metric> and overloads for std::vector<recType> input. Compile time type detection is implemented by metafunctions defined in PCFA, hence PCFA.hpp is included. In the future it would be good to move these metafunctions from PCFA.hpp to some separate file of common use.
The internals of ESN are left almost unchanged, so ESN internally still works with blaze DynamicMatrix input with vectors IN COLUMNS, and still takes such input. The new overloads simply convert vector<recType> to blaze DynaminMatrix with transposing records to columns, and converts the output back.
Also added random generator seed that was missing in ESN.

The resulting code is in iss97 branch, https://github.com/panda-official/metric/pull/102

**Comment by maxfilippov** [comment]
Note: element type cannot be long double due to BLAS limitation reported by Blaze!

**Comment by maxfilippov** [comment]
Testes all supported cases on small dataset.
Supported types of element: float, double (whereas long double is not supported by current version of BLAS)
Supported recType containers: std::vector, std::deque, blaze::DynamicVector
Also legacy input in Blaze matrices with data points in COLUMNS is still supported, as shown in example
